- name: Add Confluent Dist Yum Repo
  yum_repository:
    name: Confluent.dist
    file: confluent
    description: "Confluent repository (dist)"
    baseurl: "{{ confluent.repository.redhat.dist.baseurl }}"
    gpgcheck: "{{ confluent.repository.redhat.dist.gpgcheck }}"
    gpgkey: "{{ confluent.repository.redhat.dist.gpgkey }}"
    enabled: "{{ confluent.repository.redhat.dist.enabled }}"
  notify: yum-clean-all
- name: Add Confluent Yum Repo
  yum_repository:
    name: Confluent
    file: confluent
    description: "Confluent repository"
    baseurl: "{{ confluent.repository.redhat.main.baseurl }}"
    gpgcheck: "{{ confluent.repository.redhat.main.gpgcheck }}"
    gpgkey: "{{ confluent.repository.redhat.main.gpgkey }}"
    enabled: "{{ confluent.repository.redhat.main.enabled }}"
  notify: yum-clean-all
- meta: flush_handlers
- name: Install the Confluent Platform
  yum:
    name: "{{ confluent.package_name }}"
    state: latest
- name: Install Java
  yum:
    name: "java-1.8.0-openjdk"
    state: latest
