---
- hosts: localhost
  become: yes
  become_user: root
  vars:
    logs:
      - file: /var/log/messages
        format: "%b %d %H:%M:%S"
        group_name: /var/log/messages
      - file: /var/log/kafka/kafka-authorizer.log
        group_name: /var/log/kafka/kafka-authorizer.log
      - file: /var/log/kafka/kafka-request.log
        group_name: /var/log/kafka/kafka-request.log
      - file: /var/log/kafka/log-cleaner.log
        group_name: /var/log/kafka/log-cleaner.log
      - file: /var/log/kafka/state-change.log
        group_name: /var/log/kafka/state-change.log
      - file: /var/log/kafka/controller.log
        group_name: /var/log/kafka/controller.log
      - file: /var/log/amazon/ssm/errors.log
        group_name: /var/log/amazon/ssm/errors.log
      - file: /var/log/amazon/ssm/amazon-ssm-agent.log
        group_name: /var/log/amazon/ssm/amazon-ssm-agent.log
      - file: /var/log/amazon/ssm/hibernate.log
        group_name: /var/log/amazon/ssm/hibernate.log
    awslogs_loglevel: info
  roles:
    - cloudwatch-logs
