---
galaxy_info:
  role_name: openjdk
  author: "Fran Rodríguez"
  description: "Manage Java OpenJRE/OpenJDK environment"
  company: "DEVO Inc."
  license: "GPL-3.0"
  min_ansible_version: "2.0.0"
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - java
    - development
    - jre
    - jdk
    - openjdk
    - openjre

dependencies: []
