---
- name: broker group
  group:
    name: "{{ kafka.broker.group }}"

- name: broker user
  user:
    name: "{{ kafka.broker.user }}"
    comment: "Kafka User"
    system: yes
    group: "{{ kafka.broker.group }}"

- name: create kafka log directory
  file:
    path: /var/log/kafka
    state: directory
    mode: 0755
    owner: cp-kafka
    group: confluent

- name: update the krb5.conf config file
  template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: copy systemd service file
  template:
    src: kafka.service.j2
    dest: "{{ kafka.broker.systemd_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: copy modified start script
  copy: src=kafka-server-start dest="{{ kafka.broker.start_class }}"

- name: broker plaintext config
  template:
    src: server.properties.j2
    dest: "{{ kafka.broker.config_file }}"
    mode: 0640
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"
  when: security_mode == "plaintext"
  notify:
    - restart kafka

- name: broker ssl config
  template:
    src: server_ssl.properties.j2
    dest: "{{ kafka.broker.config_file }}"
    mode: 0640
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"
  when: security_mode == "ssl"
  notify:
    - restart kafka

- name: broker sasl_ssl config
  template:
    src: server_sasl_ssl.properties.j2
    dest: "{{ kafka.broker.config_file }}"
    mode: 0640
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart kafka

- name: broker sasl_ssl JAAS config
  template:
    src: kafka_server_jaas.j2
    dest: "{{ kafka.broker.jaas_config_file }}"
    mode: 0640
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"
  when: security_mode == "sasl_ssl"

- name: copy log4j config
  template:
    src: kafka-log4j.properties.j2
    dest: "{{ kafka.broker.log4j_config_file }}"
    mode: 0640
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"

- name: copy systemd environment file
  template:
    src: kafka-env.j2
    dest: "{{ kafka.broker.systemd_env_file }}"
    mode: 0640
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"

- name: broker configure service
  systemd:
    name: "{{ kafka.broker.service_name }}"
    enabled: "{{ kafka.broker.systemd.enabled }}"
    state: "{{ kafka.broker.systemd.state }}"

- name: Reload the systemd deamon with changes
  systemd:
    daemon_reload: yes
  notify:
    - restart kafka
