---
# file: tasks/main.yml
# Top-level installer for MongoDB.
#
# @see http://docs.mongodb.org/manual/administration/install-on-linux/
#

- name: add MongoDB official repository for CentOS
  copy: src=../files/mongodb-enterprise.repo dest=/etc/yum.repos.d/mongodb-enterprise.repo

- name: install MongoDB with specific version
  yum: name="mongodb-enterprise-{{ mongodb_version }}*"  update_cache=yes  state=present

- name: install MongoDB shell with specific version
  yum: name="mongodb-enterprise-shell-{{ mongodb_version }}*"  state=present

- name: install MongoDB tools with specific version
  yum: name="mongodb-enterprise-tools-{{ mongodb_version }}*"  state=present

- name: install MongoDB enterprise server with specific version
  yum: name="mongodb-enterprise-server-{{ mongodb_version }}*"  state=present

- name: install MongoDB mongos with specific version
  yum: name="mongodb-enterprise-mongos-{{ mongodb_version }}*"  state=present
