- name: control center create group
  group:
    name: "{{ confluent.control.center.group }}"
- name: control center create user
  user:
    name: "{{ confluent.control.center.user }}"
    comment: "Control Center User"
    system: yes
    group: "{{ confluent.control.center.group }}"
- name: control center create config
  template:
    src: control-center.properties.j2
    dest: "{{ confluent.control.center.config_file }}"
    mode: 0640
    owner: "{{ confluent.control.center.user }}"
    group: "{{ confluent.control.center.group }}"
  when: security_mode == "plaintext"
  notify:
    - restart control center
- name: control center create config
  template:
    src: control-center_ssl.properties.j2
    dest: "{{ confluent.control.center.config_file }}"
    mode: 0640
    owner: "{{ confluent.control.center.user }}"
    group: "{{ confluent.control.center.group }}"
  when: security_mode == "ssl"
  notify:
    - restart control center
- name: control center create config
  template:
    src: control-center_sasl_ssl.properties.j2
    dest: "{{ confluent.control.center.config_file }}"
    mode: 0640
    owner: "{{ confluent.control.center.user }}"
    group: "{{ confluent.control.center.group }}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart control center
- name: control center configure service
  systemd:
    name: "{{ confluent.control.center.service_name }}"
    enabled: "{{ confluent.control.center.systemd.enabled }}"
    state: "{{ confluent.control.center.systemd.state }}"
